name: Spring Boot CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-application
        path: target/*.jar
