name: Spring Boot CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-application
        path: target/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: hello-application

      - name: Copy file to server
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          nslookup $HOST
          scp -o StrictHostKeyChecking=no *.jar $USERNAME@$HOST:/home/ubuntu/apps/hello.jar

      - name: Restart service
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST sudo systemctl restart $SERVICE_NAME